const notifActionTypes = {
  SUCCESS_NOTIF: 'SUCCESS_NOTIF',
  FAILED_NOTIF: 'FAILED_NOTIF',
  GET_NOTIF_TO: 'GET_NOTIF_TO',
  SET_NOTIF_TO: 'SET_NOTIF_TO',
  GET_NOTIF_FROM: 'GET_NOTIF_FROM',
  SET_NOTIF_FROM: 'SET_NOTIF_FROM',
  ACCEPT_REQUEST: 'ACCEPT_REQUEST',
  DECLINE_REQUEST: 'DECLINE_REQUEST',
  DELETE_REQUEST: 'DELETE_REQUEST',
  SET_NOTIF_ACTIVITY: 'SET_NOTIF_ACTIVITY',
  SET_ACTIVITY_TIME: 'SET_ACTIVITY_TIME',
  GET_NOTIFICATION: 'GET_NOTIFICATION',
  SET_NOTIFICATION: 'SET_NOTIFICATION',
};

export default notifActionTypes;
