const propertyActionTypes = {
  GET_BUILDING: 'GET_BUILDING',
  SET_BUILDING: 'SET_BUILDING',
  GET_APP: 'GET_APP',
  GET_CLAIM: 'GET_CLAIM',
  SET_APP: 'SET_APP',
  SET_CLAIM: 'SET_CLAIM',
  SET_ERR: 'GET_ERR',
  GET_POLICY: 'GET_POLICY',
  SET_POLICY: 'SET_POLICY',
  GET_POLICY_CANCEL: 'GET_POLICY_CANCEL',
  SET_POLICY_CANCEL: 'SET_POLICY_CANCEL',
  CANCEL_POLICIES: 'CANCEL_POLICIES',
  FILTER_DATA: 'FILTER_DATA',
  SEARCH_DB: 'SEARCH_DB',
  GET_BUILDING_DELEGATION: 'GET_BUILDING_DELEGATION',
  SET_BUILDING_DELEGATION: 'SET_BUILDING_DELEGATION',
  GET_BUILDING_INVOICE: 'GET_BUILDING_INVOICE',
  SET_BUILDING_INVOICE: 'SET_BUILDING_INVOICE',
  GET_POLICY_CANCEL_LOGS: 'GET_POLICY_CANCEL_LOGS',
  SET_POLICY_CANCEL_LOGS: 'SET_POLICY_CANCEL_LOGS',
};

export default propertyActionTypes;
