const invoiceActionTypes = {
  GET_QBOAUTH: 'GET_QBOAUTH',
  SET_REDIRECTURL: 'SET_REDIRECTURL',
  GET_INVOICE_LIST: 'GET_INVOICE_LIST',
  SET_ERROR: 'SET_ERROR',
  SET_INVOICE_LIST: 'SET_INVOICE_LIST',
  GET_INVOICE_PDF: 'GET_INVOICE_PDF',
  SET_PDF_LOADING: 'SET_PDF_LOADING',
  SET_INVOICE_PDF: 'SET_INVOICE_PDF',
  SEND_DISPUTE: 'SEND_DISPUTE',
  FETCH_INVOICE_POLICY: 'FETCH_INVOICE_POLICY',
  SET_INVOICE_POLICY: 'SET_INVOICE_POLICY',
  SEARCH_INVOICE_NUMBER: 'SEARCH_INVOICE_NUMBER',
  SEARCH_SPINNER: 'SEARCH_SPINNER',
};

export default invoiceActionTypes;
